import type { Metadata } from "next"

import "./globals.css"

import { Open_Sans } from "next/font/google"

const openSans = Open_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-open-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${openSans.variable}`}>
      <body className={`${openSans.className} min-h-screen antialiased`}>
        {children}
      </body>
    </html>
  )
}
